correct logic for exit code

diff --git a/tests/test-smoke b/tests/test-smoke
--- a/tests/test-smoke
+++ b/tests/test-smoke
@@ -132,12 +132,11 @@ smoketest_postgres() {
     cd docker-postgres-replication || exit 1
 
     
-    if
-        VERSION=${version} p2 -t Dockerfile.p2 -o Dockerfile
-    then
-        echo "Templating failed" 1>&2
-        exit 1
-    fi
+    VERSION=${version} p2 -t Dockerfile.p2 -o Dockerfile || {
+        echo "Templating failed" 1>&2 ;
+        exit 1 ;
+    }
+
     trap "docker-compose logs; docker-compose down ; docker-compose rm -v; exit 1" EXIT INT TERM
     local compose_cmd="POSTGRES_PASSWORD=${POSTGRES_PASSWORD} docker-compose up -d --force-recreate --build"
     echo "Compose Cmd: ${compose_cmd}"
