correct logic for wget errors

diff --git a/tests/test-smoke b/tests/test-smoke
--- a/tests/test-smoke
+++ b/tests/test-smoke
@@ -111,15 +111,14 @@ smoketest_postgres() {
     wait_for_exporter
 
     # Dump the metrics to a file.
-    
-    if wget -q -O - \
-            http://localhost:${exporter_port}/metrics \
-            1> "${METRICS_DIR}/.metrics.single.${version}.prom"
-    then
-        echo "Failed on postgres ${version} (${DOCKER_IMAGE})" 1>&2
-        kill ${exporter_pid}
-        exit 1
-    fi
+    wget -q -O - \
+         http://localhost:${exporter_port}/metrics \
+         1>"${METRICS_DIR}/.metrics.single.${version}.prom" ||
+        {
+            echo "Failed on postgres ${version} (${DOCKER_IMAGE})" 1>&2
+            kill ${exporter_pid}
+            exit 1
+        }
 
     kill ${exporter_pid}
     docker kill "${CONTAINER_NAME}"
@@ -160,15 +159,13 @@ smoketest_postgres() {
     trap "docker-compose logs; docker-compose down ; docker-compose rm -v ; kill ${exporter_pid}; exit 1" EXIT INT TERM
     wait_for_exporter
 
-    
-    if
-        wget -q -O - \
-             http://localhost:${exporter_port}/metrics \
-             1> "${METRICS_DIR}/.metrics.replicated.${version}.prom"
-    then
-        echo "Failed on postgres ${version} (${DOCKER_IMAGE})" 1>&2
-        exit 1
-    fi
+    wget -q -O - \
+         http://localhost:${exporter_port}/metrics \
+         1>"${METRICS_DIR}/.metrics.replicated.${version}.prom" ||
+        {
+            echo "Failed on postgres ${version} (${DOCKER_IMAGE})" 1>&2 ;
+            exit 1 ;
+        }
 
     kill ${exporter_pid}
     docker-compose down
